### ISSUE TITLE
Change hook that init() runs on.

### ISSUE THREAD

**Issue by danieliser** [dannyvankooten/edd-helpscout#24]
Not 100% sure why, but spent about 2 hours tracking down errors that prevented a json response from the api.

Found that was getting many errors from standard functions like get_the_title which was throwing a trying to call method on a non object error.

Changing the hook from 'plugins_loaded' to 'init' resolved all issues.

The issues I did nail down were due to filters from bbPress, EDD Wishlists etc. But simply changing that hook solved all issues.

After some research that is the optimal hook to echo json and exit unless you prefer template_redirect.

I believe that there are some issues with the main query being overwritten to soon in the process that may be the culprit.

**Comment by dannyvankooten** [comment]
Hey @danieliser , sorry for the delay. 

The plugin was listening on `plugins_loaded` because of performance concerns but you are spot on, there are other (and better) ways to address that. I've changed the hook the plugin listens on to `init` in 16ef7e81b540fa3713baac9661b5d9c4c7a0fd87 .

Hope that helps!
